2015-10-05 12:44:05,326 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(80)]: --------------------------------------------------------------------------------
2015-10-05 12:44:05,327 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(81)]: JPPF Version: 5.0, Build number: 1452, Build date: 2015-03-01 07:02 CET
2015-10-05 12:44:05,327 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(82)]: starting driver with PID=8760, UUID=178C7C6A-4FCF-432A-8B62-1FCEDC12D959
2015-10-05 12:44:05,328 [INFO ][org.jppf.utils.VersionUtils.logVersionInformation(83)]: --------------------------------------------------------------------------------
2015-10-05 12:44:05,912 [INFO ][org.jppf.nio.NioConstants.getCheckConnection(83)]: NIO checks are enabled
2015-10-05 12:44:05,914 [INFO ][org.jppf.nio.StateTransitionManager.initExecutor(288)]: globalExecutor=java.util.concurrent.ThreadPoolExecutor@681564f4[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], maxSize=8
2015-10-05 18:28:19,703 [ERROR][org.jppf.comm.discovery.JPPFBroadcaster.run(133)]: No buffer space available (maximum connections reached?): Datagram send failed
java.net.SocketException: No buffer space available (maximum connections reached?): Datagram send failed
	at java.net.TwoStacksPlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(Unknown Source)
	at org.jppf.comm.discovery.JPPFBroadcaster.run(JPPFBroadcaster.java:128)
	at java.lang.Thread.run(Unknown Source)
2015-10-06 07:02:29,506 [ERROR][org.jppf.comm.discovery.JPPFBroadcaster.run(133)]: No buffer space available (maximum connections reached?): Datagram send failed
java.net.SocketException: No buffer space available (maximum connections reached?): Datagram send failed
	at java.net.TwoStacksPlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(Unknown Source)
	at org.jppf.comm.discovery.JPPFBroadcaster.run(JPPFBroadcaster.java:128)
	at java.lang.Thread.run(Unknown Source)
2015-10-06 09:31:17,214 [WARN ][org.jppf.nio.StateTransitionTask.run(89)]: error on channel SelectionKeyWrapper[id=60, readyOps=1, interestOps=0, context=ClientContext[channel=SelectionKeyWrapper[id=60], state=WAITING_JOB, uuid=0844BCE0-7650-C0B6-F183-D9FDB02CD5D3, connectionUuid=0844BCE0-7650-C0B6-F183-D9FDB02CD5D3_1, peer=false, ssl=false], nbTasksToSend=0, completedBundles={[]}] : java.io.IOException: An existing connection was forcibly closed by the remote host
